# Generated by Django 5.1.4 on 2025-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gestaopessoal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("email", models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
